language: python
python:
  - 2.7
install:
  - sudo apt-get purge python2.5
  - python bootstrap.py
  - bin/buildout -q
script:
#  - ./pre-commit-check.sh
  - bin/vvv setup.py
  - bin/vvv src/spinrewriter

notifications:
  irc:
    - "irc.freenode.org#niteoweb"
  email:
    - maintenance@niteoweb.com
