language: python
python:
  - 2.6
install:
  - sudo apt-get purge python2.5
  - sudo apt-get install python2.6
  - sudo apt-get install python-profiler build-essential
  - python bootstrap.py
  - bin/buildout
script:
  - ./pre-commit-check.sh

notifications:
  irc:
    - "irc.freenode.org#niteoweb"
  email:
    - maintenance@niteoweb.com
