language: python
python:
  - 2.7
install:
  - make
script:
  - make tests

notifications:
  irc:
    channels:
      - "irc.freenode.org#niteoweb"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
  email:
    - maintenance@niteoweb.com
